name: 'Colony Validate'
description: 'Validates colony blueprints against specific repo'
author: 'Quali'
inputs:
  space:
    description: 'Colony space'
    required: true

  fileslist:
    description: 'Whitespace separated list of files to validate'
    required: false
    
  colony_token:
    description: 'Colony longterm token'
    required: true

runs:
  using: "composite"
  steps:
    # todo: split to more steps, use python(?) 
    - id: validate
      run: ${{ github.action_path }}/run-validation.sh
      shell: bash
