name: 'Torque Validate'
description: "Validates Torque's blueprints and applications files"
author: 'Quali'
inputs:
  space:
    description: 'The Torque space your repository is connected to'
    required: true

  files_list:
    description: 'A list of files to validate in csv format'
    required: false
    
  torque_token:
    description: 'A Torque longterm token'
    required: true

  torque_url:
    description: 'Override Torque app url if needed'
    required: false
    default: "https://portal.qtorque.io"

runs:
  using: "composite"
  steps:
    - id: check-repo
      run: |
        echo "Files from the user input: ${{ inputs.files_list }}"
        [ -d ./blueprints ] || (echo "Wrong repo. No blueprints/ directory" && exit 1)
      shell: bash

    - id: build-bps-list
      run: ${{ github.action_path }}/build_bps_list.sh
      env:
        FILESLIST: ${{ inputs.files_list }}
      shell: bash

    - name: Validation Loop
      id: validate
      run: python3 ${{ github.action_path }}/validation.py
      env:
        BPS_TO_VALIDATE: ${{ steps.build-bps-list.outputs.blueprints-to-validate }}
        SPACE: ${{ inputs.space }}
        TORQUE_TOKEN: ${{ inputs.torque_token }}
        TORQUE_URL: ${{ inputs.torque_url }}

      shell: bash

branding:
  icon: 'check-circle'  
  color: 'green'
