name: 'Colony Validate'
description: 'Validates colony blueprints against specific repo'
author: 'Quali'
inputs:
  space:
    description: 'Colony space'
    required: true

  fileslist:
    description: 'A list of files to validate in csv format'
    required: false
    
  colony_token:
    description: 'Colony longterm token'
    required: true

runs:
  using: "composite"
  steps:
    - id: check-repo
      run: |
        echo "Space: ${{ inputs.space }}"
        echo "Files from the user input: ${{ inputs.fileslist }}"
        [ -d "./blueprints" ] || (echo "Wrong repo. No blueprints/ directory" && exit 1)
      shell: bash

    - id: build-bps-list
      run: ${{ github.action_path }}/build_bps_list.sh
      env:
        FILESLIST: ${{ inputs.fileslist }}
      shell: bash

    - id: extract_branch
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"

    - name: Validation Loop
      id: validate
      run: python3 ${{ github.action_path }}/validation.py
      env:
        BRANCH: ${{ steps.extract_branch.outputs.branch }}
        BPS_TO_VALIDATE: ${{ steps.build-bps-list.outputs.blueprints-to-validate }}
        SPACE: ${{ inputs.space }}
        COLONY_TOKEN: ${{ inputs.colony_token }}

      shell: bash
