name: 'Torque Validate'
description: "Validates Torque's blueprints and applications files"
author: 'Quali'
inputs:
  space:
    description: 'The Torque space your repository is connected to'
    required: true

  files_list:
    description: 'A list of files to validate in csv format'
    required: false
    
  torque_token:
    description: 'A Torque longterm token'
    required: true

  torque_hostname:
    description: 'Override Torque app url if needed'
    required: false
    default: "portal.qtorque.io"

runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.files_list }}
  env:
    TORQUE_SPACE: ${{ inputs.space }}
    TORQUE_TOKEN: ${{ inputs.torque_token }}
    TORQUE_HOSTNAME: ${{ inputs.torque_hostname }}

branding:
  icon: 'check-circle'  
  color: 'green'
